version: "3.7"
volumes:
 todo-mysql-data:
networks:
 reseau-todo:
services:
 mysql:
  image: mysql:5.7
  volumes:
   - todo-mysql-data:/var/lib/mysql
  networks:
   - reseau-todo
  environment:
   MYSQL_DATABASE: todos
   MYSQL_ROOT_PASSWORD: root
 app:
  image: node:10-alpine
  command: sh -c "yarn install && yarn run dev"
  ports:
   - 3000:3000
  working_dir: /app
  volumes:
   - ./:/app
  networks:
   - reseau-todo
  environment:
   MYSQL_HOST: mysql
   MYSQL_USER: root
   MYSQL_PASSWORD: root
   MYSQL_DB: todos



