version: "3.7"
volumes:
  todo-mysql-data:
networks:
  reseau-todo:
services:
  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    networks:
      - reseau-todo
    environment:
      MYSQL_DATABASE: todos
      MYSQL_ROOT_PASSWORD: root
  app:
    image: fannyvazart/todo-app:1.1.0
    ports:
      - 3000:3000
    networks:
      - reseau-todo
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: todos
